name: build and deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry config virtualenvs.in-project true --local
          poetry install

      - name: Setup DVC
        run: |
          dvc remote modify --local gdrive-remote gdrive_client_id '${{ secrets.DVC_GDRIVE_CLIENT_ID }}'
          dvc remote modify --local gdrive-remote gdrive_client_secret '${{ secrets.DVC_GDRIVE_CLIENT_SECRET }}'
          dvc remote modify --local gdrive-remote-release gdrive_client_id '${{ secrets.DVC_GDRIVE_CLIENT_ID }}'
          dvc remote modify --local gdrive-remote-release gdrive_client_secret '${{ secrets.DVC_GDRIVE_CLIENT_SECRET }}'

      - name: Download DVC Remote Files
        run: |
          source .venv/bin/activate
          dvc pull -r gdrive-remote

      - name: Build
        run: bash ./scripts/build.sh build
      
      - name: Push to remote
        run: |
          rsync -av --exclude='*.dvc' --exclude='landing' _build/* pkg/
          dvc add -r gdrive-remote-release pkg/*
          dvc push -r gdrive-remote-release
      
      - name: Push to Data Registry
        run: |
          source .venv/bin/activate
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git clone https://github.com/aldencabajar/open-ph-data-registry.git
          cp pkg/*.dvc open-ph-data-registry/
          cd open-ph-data-registry
          git add *.dvc
          git commit -m "Update DVC files from data platform [skip ci]"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/aldencabajar/open-ph-data-registry.git HEAD:main


